/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package gradle.test.project

class App {
    String getGreeting() {
        return null
        //return 'Hello world.'
    }

    static void main(String[] args) {
        println new App().greeting
    }
}
